## This issuer will only be provisioned if certmanger has been deployed into the cluster. 

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: springapp-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <your-email>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: springapp-priv
    # Enable the HTTP-01 challenge provider
    solvers:
    - selector:
        dnsNames:
          - "<domainname>" #domain name for java spring app
      dns01:
        route53:
          region: us-west-2
          # The AWS access key ID can be specified using the literal accessKeyID parameter
          # or retrieved from a secret using the accessKeyIDSecretRef
          # If using accessKeyID, omit the accessKeyIDSecretRef parameter and vice-versa
          hostedZoneID: <aws-hostedzone-id>
          accessKeyIDSecretRef:
            name: goku
            key: kamehameha
          secretAccessKeySecretRef:
            name: goku
            key: spiritbomb

